project:
  type: book

book:
  title: "Remote sensing Diary"
  author: "Norah Jones"
  date: "1/20/2026"
  chapters:
    - index.qmd
    - Week1.qmd
    - Week2.qmd 
    - Week3.qmd 
    - Week4.qmd 
    - Week5.qmd 
    - Week6.qmd
    - Week7.qmd
    - Week8.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

